version: '3.8'

services:
    db:
        image: 'postgres:13'
        container_name: postgres_db
        environment:
            POSTGRES_HOST: db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: restaurant
        volumes:
            - './db/data:/var/lib/postgresql/data'
            - './db/init.sql:/docker-entrypoint-initdb.d/init.sql'
            - './db/dataset:/dataset'
        ports:
            - '5432:5432'